controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

paragraph_action:
    path:     /run-paragraph-action
    defaults: { _controller: "App:ParagraphAction:listParagraphAction" }
    methods:  GET 