controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

paragraph_action:
    path:     /run-paragraph-action
    defaults: { _controller: "App\\Controller\\ParagraphActionController::listParagraphAction" }
    methods:  GET

paragraph_equipment:
    path:     /run-paragraph-equipment
    defaults: { _controller: "App\\Controller\\ParagraphEquipmentController::listParagraphEquipmentAction" }
    methods:  GET

hero_equipment:
    path:     /get-hero-equipment
    defaults: { _controller: "App\\Controller\\HeroEquipmentController::listHeroEquipmentAction" }
    methods:  GET